# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Deno - Code Review"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "edited"
      - "opened"
      - "reopened"
      - "synchronize"
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:
permissions:
  contents: "read"
jobs:
  main:
    name: "${{matrix.runs-on}}"
    strategy:
      matrix:
        runs-on:
          - "ubuntu-latest"
      fail-fast: false
    uses: "hugoalh/hugoalh/.github/workflows/call-deno-code-review-0.yml@main"
    with:
      runs-on: "${{matrix.runs-on}}"
